apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gearpit-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nordiwnd/GearPit.git
    targetRevision: dev/01
    path: manifests/apps/gearpit-web/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true