apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gearpit-previews
spec:
  generators:
    - pullRequest:
        github:
          owner: nordiwnd
          repo: gearpit
          tokenRef:
            secretName: github-token
            key: token
        requeueAfterSeconds: 60
  template:
    metadata:
      name: 'gearpit-pr-{{number}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/nordiwnd/gearpit.git'
        targetRevision: '{{branch}}' 
        path: 'manifests/apps/gearpit-web/overlays/preview'
        kustomize:
          images:
            - name: gearpit-web
              newTag: 'sha-{{head_sha}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'gearpit-pr-{{number}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m