---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: argocd
spec:
  encryptedData:
    token: AgCwNXWQ+UvseiVt4BLTRHO1yaHW096MwOzPAx4DjDL/0ryYVHL5tZfqVat846OHjASHiX14VNx7OEARSLkXt4ec3X3lWzdP2t/o1KsSXfhm/qQZUMBJywZZQ+1ZO0IaDvs9Ln98uO7A5hqnq8ki02ghgBV6QlEG2mT28VRNYG6pUKafvvfE44G0WMbWW41ofEJt5bO6/qv6wQnuCGDSNx6iVpxuNkw5RKO/SUTZuYcdwzGAmunLKuZBd2fRUkpFsern0W7svc2e3L0R4O4TCbGmqdz5zIcoVqXbTYicXNGLe4CgGNsaRjw+xMvXbdcHk+K9hd+Ok/pISL/3lRJyVtj0FisKpNgpZjfylQhuFSpO2f9a2SaM1AjGJyEkLew90cHipUoXy42A4o6UPUsZGqK3cwDBrcUtSYNMUW/4xqaABIIKf8cRICab1Ul0wc3dNIcbogpnojqhmES+DWxrvJ93HymmdeAcDNshGnMrR3xbG51Ljd11T0MYhvMKqhTqKWaZyxFmznB7DlukKQct0GgOWtFY7kJ2rodF024bvMlWgqBCF8W9q9cFqiw8SWiZC98a3K3jkN76A6XyIddXkfGvF7wqljvSmuetzvwQDDzDqCoelzPhaX5CIsefV8JP0SnDIGGe+2VDd07kJKD3pHsjNNnpE+C6ylo831OKXEEe6jHQk+8fbwripUAQKLvs4/FqDDCDI4pHJTnwrjmpo7vkOAOtmf5HZNB9/W4Ry8UR4kf60/hO4mKN
  template:
    metadata:
      name: github-token
      namespace: argocd
